===18.04.2018=== 1) I have got a strange error when tried run LoginServlet. here is error stacktrace:
Exception

javax.servlet.ServletException: Servlet execution threw an exception
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

java.lang.ExceptionInInitializerError
	net.chemodurov.productfromthemanufacturer.dao.HibernateSessionFactory.buildSessionFactory(HibernateSessionFactory.java:17)
	net.chemodurov.productfromthemanufacturer.dao.HibernateSessionFactory.<clinit>(HibernateSessionFactory.java:7)
	net.chemodurov.productfromthemanufacturer.dao.HibernateUserDAOImpl.validate(HibernateUserDAOImpl.java:56)
	net.chemodurov.productfromthemanufacturer.controller.LoginServlet.doGet(LoginServlet.java:24)
	net.chemodurov.productfromthemanufacturer.controller.LoginServlet.doPost(LoginServlet.java:13)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

java.lang.NoClassDefFoundError: org/hibernate/cfg/Configuration
	net.chemodurov.productfromthemanufacturer.dao.HibernateSessionFactory.buildSessionFactory(HibernateSessionFactory.java:13)
	net.chemodurov.productfromthemanufacturer.dao.HibernateSessionFactory.<clinit>(HibernateSessionFactory.java:7)
	net.chemodurov.productfromthemanufacturer.dao.HibernateUserDAOImpl.validate(HibernateUserDAOImpl.java:56)
	net.chemodurov.productfromthemanufacturer.controller.LoginServlet.doGet(LoginServlet.java:24)
	net.chemodurov.productfromthemanufacturer.controller.LoginServlet.doPost(LoginServlet.java:13)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

I suppose that reason of this error is hibernate can't create sessionFactory. But i'm not sure.